services:
  database:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./database/pagila-schema.sql:/docker-entrypoint-initdb.d/01-pagila-schema.sql
      - ./database/pagila-data.sql:/docker-entrypoint-initdb.d/02-pagila-data.sql
    restart: always

volumes:
  pgdata:
